apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: ludovicm67/resto-demo-app-back
    context: src/backend
  - image: ludovicm67/resto-demo-app-front
    context: src/front
  - image: ludovicm67/resto-demo-app-worker
    context: src/worker
deploy:
  kustomize:
    path: k8s/overlays/vsphere/
