apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: ludovicm67/resto-demo-app-room
    context: room
  - image: ludovicm67/resto-demo-app-dish
    context: worker
deploy:
  kubectl:
    manifests:
    - k8s/room-dep.yaml
    - k8s/worker-dish.yaml
