apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: ludovicm67/resto-demo-app-back
    context: backend
  - image: ludovicm67/resto-demo-app-front
    context: front
  - image: ludovicm67/resto-demo-app-worker
    context: worker
deploy:
  kustomize:
    path: k8s/overlays/vsphere/
