apiVersion: v1
kind: Service
metadata:
  name: resto-demo-app-back
  annotations:
    scrape_metrics: "true"
spec:
  type: ClusterIP
  selector:
    app: resto-demo-app-back
  ports:
  - port: 3000
    targetPort: 3000
