apiVersion: apps/v1
kind: Deployment
metadata:
  name: resto-demo-app-front
spec:
  template:
    spec:
      containers:
      - name: resto-demo-app-front
        env:
        - name: BACKEND_URL
          value: https://resto-back.192.168.85.40.xip.io
