apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  variant: vsphere

namespace: resto-demo-app

bases:
- ../../base

resources:
- cert-secret.yaml
- ingress-back.yaml
- ingress-front.yaml

patchesStrategicMerge:
- deployment-front.yaml
