apiVersion: apps/v1
kind: Deployment
metadata:
  name: resto-demo-app-worker-drink
spec:
  selector:
    matchLabels:
      app: resto-demo-app-worker-drink
  template:
    metadata:
      labels:
        app: resto-demo-app-worker-drink
    spec:
      containers:
      - name: resto-demo-app-worker
        image: ludovicm67/resto-demo-app-worker
        resources:
          requests:
            memory: "30Mi"
            cpu: "1m"
          limits:
            memory: "75Mi"
            cpu: "30m"
        env:
        - name: WORKER_NAME
          value: drink
        - name: WORKER_DURATION
          value: "5"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 80
